name: Dockerfile Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  dockerfile-policy-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/Dockerfile*
            **/*.dockerfile
          files_ignore: |
            .github/**

      - name: Run Dockerfile security tests
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: instrumenta/conftest-action@master
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          policy: dockerfile-policy.rego

      - name: No Dockerfiles changed
        if: steps.changed-files.outputs.any_changed == 'false'
        run: echo "No Dockerfiles were changed in this commit"
